version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    links:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - 8088:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret  
      PMA_HOST: mysql
      PMA_PORT: 3306   

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=myoctobercms"
    ports:
        - "33061:3306"  

volumes:
  dbdata: